### ISSUE TITLE
Maven artifacts are not compatible with Java versions below 8

### ISSUE THREAD

**Issue by mikehepple** [TAXIIProject/java-taxii#12]
When attempting to use the library in Java 7 we get the following error:

`Caused by: java.lang.UnsupportedClassVersionError: org/mitre/taxii/messages/TaxiiXml : Unsupported major.minor version 52.0`

Could future versions be compiled with 1.7 compatibility?

(Same issue was raised to the java-stix project - https://github.com/STIXProject/java-stix/issues/1)

**Comment by jasenj1** [comment]
Yes, the library could target 1.7.
I've published a new release 1.1.0.1 which targets Java 1.7.
It make take a while for it to appear in the central Maven repository.
If it solves your problem, please close this issue.

**Comment by mikehepple** [comment]
Yup, that worked great. Thanks for the quick response!

**Comment by mikehepple** [comment]
I ran the wrong unit test.. it's still compiled for Java 8:

```
~/.m2/repository/org/mitre/taxii/taxii/1.1.0.1$ javap -verbose org/mitre/taxii/ContentBindings.class | grep major
  major version: 52
```

**Comment by jasenj1** [comment]
Whoops. Very sorry about that. I rebuilt it and this time confirmed the major version. Republished as the same version. Should hit the central repository soon.

**Comment by mikehepple** [comment]
I can confirm it's on central (unfortunately our nexus is refusing to pick it up.. but we'll sort it :))

Thanks again!
